### ISSUE TITLE
Optimize image size

### ISSUE THREAD

**Issue by LaszloGombos** [abiosoft/colima-core#3]
Noticed that the default boot partition is much larger than needed.

/dev/vda16        881M   40M  780M   5% /boot
/dev/vda15        105M  6.1M   99M   6% /boot/efi

We should consider making them smaller or at least zero them out so that qcow2 can compress.

CC @abiosoft

**Comment by abiosoft** [comment]
Another thing to note, considering that the cloud-image is just around 200MB before adding extra packages, the boot partition may not have much of an influence on the final size i.e. probably zeroed out already.

**Comment by abiosoft** [comment]
> I have not looked, but now I am thinking that taking the stable version of docker is much larger than the distro version of docker as the upstream version might package some of the dependencies so that the final image has two copies.

I also prefer the distro version of docker for same reasons but there were issues with the distro version (https://github.com/abiosoft/colima/issues/856, https://github.com/abiosoft/colima/issues/863) that were only fixed after switching to official version.

**Comment by abiosoft** [comment]
> I am wondering why not to use the LTS (22.04) version of Ubuntu (especially given that anyways we do not use the distro version of docker). Can you help understanding this ?

Because there is no minimal ubuntu image for 22.04 LTS arm64. It only exists for amd64.
